// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("ReproCsv")>]
[<assembly: AssemblyProductAttribute("ReproCsv")>]
[<assembly: AssemblyDescriptionAttribute("Project has no summmary; update build.fsx")>]
[<assembly: AssemblyVersionAttribute("0.0.1")>]
[<assembly: AssemblyFileVersionAttribute("0.0.1")>]
[<assembly: AssemblyConfigurationAttribute("Debug")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "ReproCsv"
    let [<Literal>] AssemblyProduct = "ReproCsv"
    let [<Literal>] AssemblyDescription = "Project has no summmary; update build.fsx"
    let [<Literal>] AssemblyVersion = "0.0.1"
    let [<Literal>] AssemblyFileVersion = "0.0.1"
    let [<Literal>] AssemblyConfiguration = "Debug"
