// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("ReproCsv")>]
[<assembly: AssemblyProductAttribute("ReproCsv")>]
[<assembly: AssemblyDescriptionAttribute("Project has no summmary; update build.fsx")>]
[<assembly: AssemblyVersionAttribute("1.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0")>]
[<assembly: AssemblyConfigurationAttribute("Debug")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "ReproCsv"
    let [<Literal>] AssemblyProduct = "ReproCsv"
    let [<Literal>] AssemblyDescription = "Project has no summmary; update build.fsx"
    let [<Literal>] AssemblyVersion = "1.0"
    let [<Literal>] AssemblyFileVersion = "1.0"
    let [<Literal>] AssemblyConfiguration = "Debug"
